name: espcontrol
description: Client App for the ESP Stepper Controller
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  http: ^0.13.3
  flutter_switch: ^0.3.1
  multicast_dns: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
